---
title: "wk4_homework"
output: html_document
date: "2024-10-28"
---

```{r}
library(sf)
library(here)
library(janitor)
library(tidyverse)
library(terra)
library(ggplot2)
```

Read data
```{r}
world_spacedata <- sf::st_read(here("prac4_data", "World_Countries_(Generalized)_9029012925078512962 (1).geojson"))

#你需要使用read_csv读取csv文件 而不是st_read
Composite_indices <- read_csv(here("prac4_data", "HDR23-24_Composite_indices_complete_time_series.csv"))
```

Select the data we required
```{r}
#有点乱
# Gender_inequality <- Composite_indices %>%
#   select(iso3, contains("gii"))
# 
# Gender_inequality_2010_2019 <- Gender_inequality %>%
#   dplyr::select(iso3,gii_2010:gii_2019)
# 
# 
# Gender_Inequality_2010_2019 <- Gender_inequality_2010_2019 %>%
#   mutate(across(everything(), ~ ifelse(. == "", NA, .))) %>%
#   mutate(across(everything(), ~ ifelse(is.na(.), 0, .)))
# 
# Gender_Inequality_2010_2019_N <- Gender_Inequality_2010_2019 %>%
#   mutate(gii_2019 = as.numeric(gii_2019),
#          gii_2010 = as.numeric(gii_2010))
# 
# 
# Gii_difference <- Gender_Inequality_2010_2019_N %>%
#   mutate(gii19_gii10 = gii_2019 - gii_2010)
```

```{r}
Gii_difference <- Composite_indices %>%
  select(iso3, country, gii_2010, gii_2019) %>% 
  mutate(gii_2010 = as.numeric(gii_2010),
         gii_2019 = as.numeric(gii_2019),
         gii19_gii10 = gii_2019 - gii_2010
         )

```


Transfer the country code and join the data
```{r}
#install.packages("countrycode")
library(countrycode)

world_country <- world_spacedata %>%
  mutate(ISO3 = countrycode(ISO,"iso2c","iso3c"))

#join the data
world_gii_2010_2019 <- world_country %>%
  left_join(Gii_difference, by = c("ISO3" = "iso3"))
```

```{r}

library(tmap)
tmap_mode("plot")

tm_shape(world_gii_2010_2019) + 
  tm_polygons("gii19_gii10",
              style="pretty",             # 自动选择合适的分段方式
              palette="RdBu",             # 使用红蓝分段色彩方案
              breaks=5,                   # 指定分成5个区间
              title="Numbers of years",
              midpoint = 0  
              ) +
  tm_compass(position = c("left", "bottom"), type = "arrow") +
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Difference of gender inequality index between 2019 and 2011",
            legend.position = c("right", "bottom"))


```

